---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart nginx-ui
  ansible.builtin.systemd:
    name: "{{ nginx_ui_service_name }}"
    state: restarted
  when: nginx_ui_service_state == 'started'
